### PR TITLE
`--archive` + `--pdf` logging

### LINKED ISSUE #69: Improve re-zip logging about `--pdf` option
The `--archive` mode is specific to epub and mobi. If the user misunderstand this and provide the `--pdf` option along with `--archive`, some log should notify them that `--pdf` is ignored and Reliure doesn't work that way.

### PR DESCRIPTION
**Pull request by BlueCutOfficial**
Fixes #69.

This PR initially intends to display a simple log when the `--pdf` option is passed with `--archive`, to notify the user that these options are incompatible and `--pdf` will be ignored.

Due to how early in the process the archive task was located, getting this log printed before the process exit required reworking the task ordering a bit. 

(Note that this work will be useful later since we want to give users the possibility to regenerate the mobi out of the re-archive.)

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -47,14 +42,21 @@ const options = getOptions()
     settings.kindlegenPath = undefined
   }
 
+  let { formats } = await getFormats(settings, options)
+
+  if (options.archive) {
+    await archive(options.config, `${configPath}.epub`)
+    success(`Created archive ${configPath}.epub`)
```
Comment (GreatWizard) [inline src/index.js:49]:
```suggestion
    success(`Created archive ${options.config}.epub`)
```

**Review by GreatWizard — APPROVED** [review]
